namespace SqlConstraintHelper.Core.Models
{
    /// <summary>
    /// Represents a table in the query builder
    /// </summary>
    public class QueryTable
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string SchemaName { get; set; } = string.Empty;
        public string TableName { get; set; } = string.Empty;
        public string Alias { get; set; } = string.Empty;
        public string FullName => $"{SchemaName}.{TableName}";
        public string DisplayName => string.IsNullOrEmpty(Alias) ? TableName : $"{TableName} AS {Alias}";
        public List<QueryColumn> Columns { get; set; } = new();
        public bool IsBaseTable { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
    }

    /// <summary>
    /// Represents a column that can be selected or used in conditions
    /// </summary>
    public class QueryColumn
    {
        public string ColumnName { get; set; } = string.Empty;
        public string DataType { get; set; } = string.Empty;
        public bool IsSelected { get; set; }
        public bool IsInJoinCondition { get; set; }
        public bool IsInWhereClause { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsForeignKey { get; set; }
        public string? AggregateFunction { get; set; } // SUM, COUNT, AVG, etc.
        public string? SortOrder { get; set; } // ASC, DESC
        public int? SortPriority { get; set; }
    }

    /// <summary>
    /// Represents a JOIN between two tables
    /// </summary>
    public class QueryJoin
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid LeftTableId { get; set; }
        public Guid RightTableId { get; set; }
        public JoinType JoinType { get; set; } = JoinType.Inner;
        public List<JoinCondition> Conditions { get; set; } = new();
        public bool IsAutoGenerated { get; set; }
        public string? ConstraintName { get; set; }
    }

    /// <summary>
    /// A single join condition (column = column)
    /// </summary>
    public class JoinCondition
    {
        public string LeftColumn { get; set; } = string.Empty;
        public string RightColumn { get; set; } = string.Empty;
        public string Operator { get; set; } = "=";
    }

    /// <summary>
    /// WHERE clause condition
    /// </summary>
    public class WhereCondition
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid TableId { get; set; }
        public string ColumnName { get; set; } = string.Empty;
        public string Operator { get; set; } = "=";
        public string Value { get; set; } = string.Empty;
        public string LogicalOperator { get; set; } = "AND"; // AND, OR
    }

    /// <summary>
    /// Complete query definition
    /// </summary>
    public class QueryDefinition
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Name { get; set; } = "New Query";
        public List<QueryTable> Tables { get; set; } = new();
        public List<QueryJoin> Joins { get; set; } = new();
        public List<WhereCondition> WhereConditions { get; set; } = new();
        public bool IsDistinct { get; set; }
        public int? TopCount { get; set; }
        public List<string> GroupByColumns { get; set; } = new();
        public string? HavingClause { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public DateTime ModifiedDate { get; set; } = DateTime.Now;

        public string GetSelectedColumnsCount()
        {
            return Tables.Sum(t => t.Columns.Count(c => c.IsSelected)).ToString();
        }

        public string GetTableCount()
        {
            return Tables.Count.ToString();
        }
    }

    /// <summary>
    /// Query optimization suggestion
    /// </summary>
    public class QuerySuggestion
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public SuggestionType Type { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string? SqlExample { get; set; }
        public SuggestionSeverity Severity { get; set; } = SuggestionSeverity.Info;
        public bool CanAutoFix { get; set; }
    }

    /// <summary>
    /// Join path between two tables
    /// </summary>
    public class JoinPath
    {
        public List<string> Tables { get; set; } = new();
        public List<ForeignKeyInfo> ForeignKeys { get; set; } = new();
        public int Distance { get; set; }
        public bool IsDirect { get; set; }

        public string GetPathDescription()
        {
            return string.Join(" → ", Tables);
        }
    }

    public enum JoinType
    {
        Inner,
        LeftOuter,
        RightOuter,
        FullOuter,
        Cross
    }

    public enum SuggestionType
    {
        MissingJoin,
        RedundantJoin,
        MissingIndex,
        SelectStar,
        MissingWhereClause,
        CartesianProduct,
        ImplicitConversion,
        SuboptimalJoinOrder
    }

    public enum SuggestionSeverity
    {
        Info,
        Warning,
        Error,
        Performance
    }

    /// <summary>
    /// Query execution statistics
    /// </summary>
    public class QueryStatistics
    {
        public long EstimatedRows { get; set; }
        public double EstimatedCost { get; set; }
        public int JoinCount { get; set; }
        public int TableScanCount { get; set; }
        public int IndexSeekCount { get; set; }
        public List<string> MissingIndexes { get; set; } = new();
        public List<string> Warnings { get; set; } = new();
    }
}